# Configuracoes de Treinamento
interactive: false
model_name: "convnext_small"
model_version: "fb_in22k_ft_in1k"

num_epochs: 1
batch_size: 4
learning_rate: 0.0001
num_workers: 4
pin_memory: true
persistent_workers: true
prefetch_factor: 2
image_size: [224, 224]
data_augmentation: true

# Folds
num_folds: 5
fold_idx: null
split_random_state: 42

# OneCycleLR e Early Stopping
early_stop_patience: 5
onecycle_pct_start: 0.1
onecycle_anneal_strategy: "cos"
onecycle_div_factor: 100.0
onecycle_final_div_factor: 10000.0
freeze_backbone_epochs: 0

# Diretorios de saida
save_dir: "/home/luis/Dev/Classificação/CEYEQ/weights"
viz_dir: "/home/luis/Dev/Classificação/CEYEQ/vizualizacoes"
arch_dir: "/home/luis/Dev/Classificação/CEYEQ/arquiteturas"
results_dir: "/home/luis/Dev/Classificação/CEYEQ/resultados"

# Modelo
pretrained: true
num_classes: 3
dropout_rate: 0.3


data_dir: "/home/luis/Dev/Classificação/CEYEQ/Balanceado/train"
metadata_csv: "/home/luis/Dev/Classificação/CEYEQ/data/eyeq_train_dataset_balanced.csv"

test_data_dir: "/home/luis/Dev/Classificação/CEYEQ/FQS/images" 
test_csv: "/home/luis/Dev/Classificação/CEYEQ/FQS/FIQS_dataset.csv"

local_cache_dir: "${CGL_LOCAL_CACHE_DIR:-}"
filepath_column: "image"
label_column: "quality"
class_name_column: null
